//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInfoSystem.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Students
    {
        public int Id { get; set; }
        
        [Required]
        [RegularExpression("^[a-zA-Z]*$")]
        public string StudentName { get; set; }
        
        [Required]
        [RegularExpression("^[a-zA-Z]*$")]
        public string StudentSurname { get; set; }
        
        [Range(0,100)]
        [RegularExpression("^[0-9]*$")]
        public string StudentNo { get; set; }
        public int ClassId { get; set; }
    
        public virtual Classes Classes { get; set; }
    }
}
